### ISSUE TITLE
release a binary on github

### ISSUE THREAD

**Issue by m040601** [srvaroa/repocket#2]
Any chance you could actualy release it as a binary on github ?

Releasing a binary, just makes your tool available for someone who just wants to check it out quickly.

Not everyone has the entire go distribution installed or as a simple user is familiar with compiling.Besides that releasing a binary, would make it easier for others to create a package for a Linux distro, based on the binary (ex. Archlinux AUR).i

Do you know this tool, https://github.com/goreleaser/goreleaser ?

https://help.github.com/en/articles/creating-releases
you can also use:

travis, https://blog.questionable.services/article/build-go-binaries-travis-ci-github/
circleci, https://circleci.com/blog/publishing-to-github-releases-via-circleci/

**Comment by srvaroa** [comment]
Sure, I will once I have some spare time.  Feel free to PR a release script of course :)

**Comment by srvaroa** [comment]
https://github.com/srvaroa/repocket/releases
