### ISSUE TITLE
use the XDG standard $HOME/.config/repocket/ for the configuration file

### ISSUE THREAD

**Issue by m040601** [srvaroa/repocket#3]
Thanks againg for your work in this app. Looks very promising. I like the concept of moving and shuffling the archived/deleted articles.

Would you consider making this app more standards compliant  and avoiding creating dedicated folders directly inside "polluting" your home folder ? 

https://wiki.archlinux.org/index.php/XDG_Base_Directory

Storing the config file in something like,
$HOME/.config/repocket/repocketrc or $HOME/.config/repocket/config
 ? Any extra tokens or config sent from pocket would also stay in this directory.
Files would go to $HOME/.local/share/repocket/articles/deleted, archived etc

It might give you a little extra work now, but it will save you so much headaches in the future. You would also ensure a safe and unique place for your app's config and files in the user system.

There are many many pocket apss scripts on github (go , python, node ). Many forget this. Many are simlpy named "pocket" , "getpocket", or contain the word "pocket" in a not undistinguishable way.. They all  need to create "pocketrc" , config, token etc files and folders randomly spread and conflicting inside your HOME dir.

There is for example an older go cli app that also instals a cli simply called "pocket", https://github.com/junkbl
I test many pocket cli apps on my system and sometimes find it confusing and loose track of which app, executable, token credentials config file etc belongs to whom.

Additionally it would make it easy to create a package for distributing in a Linux distribution. I'd like to package your app to create an AUR Archlinux package.

Thanks in advance

**Comment by srvaroa** [comment]
Yes, I had this in my (mental) backlog.  PRs welcome, of course :)

**Comment by srvaroa** [comment]
Done at 1936cabccd57609c3ec0b9b7fcdc56c5e1ea924d
